all:
	pdflatex -interaction=nonstopmode teorica.tex
	pdflatex -interaction=nonstopmode practica.tex

teorica:
	pdflatex -interaction=nonstopmode teorica.tex

practica:
	pdflatex -interaction=nonstopmode practica.tex
