all: clase1-2021-01-28.mp4, clase_funciones-2021-04-08.mp4, clase_bayes2-2021-06-30.mp4, clase_sumproduct_1_2021-06-02.mp4, clase_sumproduct_2_2021-06-16.mp4

clase1-2021-01-28.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2021.1/clase1-2021-01-28.mp4

clase_funciones-2021-04-08.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2021.1/clase_funciones-2021-04-08.mp4

clase_bayes2-2021-06-30.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2021.1/clase_bayes2-2021-06-30.mp4

clase_sumproduct_1_2021-06-02.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2021.1/clase_sumproduct_1_2021-06-02.mp4

clase_sumproduct_2_2021-06-16.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2021.1/clase_sumproduct_2_2021-06-16.mp4
