all: main.pdf practica0.pdf teorica-sumprod.pdf teorica1.pdf

main.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2022.1/main.pdf

practica0.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2022.1/practica0.pdf

teorica-sumprod.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2022.1/teorica-sumprod.pdf


teorica1.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2022.1/teorica1.pdf
