all: 0-programa.pdf 1-intro.pdf 2-causa.pdf 3-dato.pdf 4-tiempo.pdf 5-decision.pdf 6-hackaton.pdf

0-programa.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2023.1/0-programa.pdf

1-intro.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2023.1/1-intro.pdf

2-causa.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2023.1/2-causa.pdf

3-dato.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2023.1/3-dato.pdf

4-tiempo.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2023.1/4-tiempo.pdf

5-decision.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2023.1/5-decision.pdf

6-hackaton.pdf:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2023.1/6-hackaton.pdf
