

cap3.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap3.mp4

cap4.2.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap4.2.mp4

cap5.1.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap5.1.mp4
	
cap5.2.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap5.2.mp4

cap6.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap6.mp4

cap7.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap7.mp4

cap8.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap8.mp4

cap10.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap10.mp4
	
cap11.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap11.mp4

cap14.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap14.mp4

cap15.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/cap15.mp4

pre-VAE.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/curso/releases/download/2020.2/pre-VAE.mp4
