all: simple_gamble.pdf simple_gamble_incesto.pdf

remake: clear_all all

simple_gamble_incesto.pdf:
	/usr/bin/python3 simple_gamble_incesto.py

simple_gamble.pdf:
	/usr/bin/python3 simple_gamble.py

clear_all: 
	rm *.pdf
	rm *.png


