# ffmpeg -f concat -i input.txt -c copy output.mp4
# input.txt:
# file 'clase1.1.mp4'
# file 'clase1.2.mp4'
#
# size:
# ffmpeg -i input.mp4 -vcodec libx265 -crf 28 output.mp4

opciones:
	echo "opciones: v2021.2, v2021.1, v2020"

all: v2021.2, v2021.1, v2020


v2021.1:
	make -C 2021.1/
