all: clase1_0.mp4, clase1_1.mp4, clase1_2.mp4, clase2_0.mp4, clase2_1.mp4

clase1_0.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/seminario/releases/download/v2020.1.1/clase1_0.mp4

clase1_1.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/seminario/releases/download/v2020.1.1/clase1_1.mp4
	
clase1_2.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/seminario/releases/download/v2020.1.1/clase1_2.mp4
	
clase2_0.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/seminario/releases/download/v2020.1.2/clase2_0.mp4

clase2_1.mp4:
	wget https://github.com/BayesDeLasProvinciasUnidasDelSur/seminario/releases/download/v2020.1.2/clase2_1.mp4
